### PR TITLE
Copy over missing evaluator changes

### PR DESCRIPTION
**Pull request by dm0n3y**
https://github.com/hazelgrove/hazel/pull/756 didn't have all of the evaluator changes. This PR fixes that.

### CODE REVIEW

**Comment by mirryi** [comment]
@dmoon1221 `ProgramEvaluator` operates on the old `Program.t`; do we want to reintroduce something like that or just pass a tuple of `Statics.map, Term.UExp.t` directly?

**Comment by dm0n3y** [comment]
I changed the request type to DHExp, which is all that was needed afaict. Interface.re is the new Program-level API.

**Comment by mirryi** [comment]
We're doing elaboration main thread side then?

**Comment by dm0n3y** [comment]
Oh hm I guess never committed that change. I'll let you decide that based on what you did before. Passing in term + map should work too.

**Comment by mirryi** [comment]
The map might be a little big to be passing over to the web worker; we can do elaboration client side I guess. Is `Interface` supposed to be concerned with UI view or evaluation? Maybe we could move `Interface.{evaluate, evaluation_result}` to `ProgramEvaluator`.

**Comment by dm0n3y** [comment]
Interface is supposed to centralize general program-level semantic operations. Personally I'd err on the side of keeping things as is for now with the intention of reconsidering/merging APIs in a subsequent PR, but do what you gotta do to get things working.

**Comment by mirryi** [comment]
Yeah, sure that's fine for now. I'll make the request `DHExp.t` and make `ProgramEvaluator` hook into `Interface`.

**Comment by mirryi** [comment]
Is `DoesNotElaborate` getting raised supposed to be a bug or no? We need to catch those somewhere. More broadly, we need to change the calls to `Interface.evaluation_result` inside the ui views to use the web worker model again like in dev.

**Comment by dm0n3y** [comment]
Yes it getting raised would signal a bug

**Comment by dm0n3y** [comment]
Re: changing calls to `Interface.evaluation_result`. What's involved there? Is it just changing the function call?

**Comment by mirryi** [comment]
The web worker model is asynchronous, so instead of making synchronous call to `evaluation_result`, evaluation needs to occur asynchronously when the program changes and pushes a model update when complete, which will then update a "current result" that is displayed

**Comment by dm0n3y** [comment]
@cyrus- checking in. @mirryi and I talked offline. There's going to be a single asynchronously updated `ModelResult` in the top-level model. This should work with the multiple cells in school mode using the approach we discussed yesterday. School cells will get spliced together using a cell-separator operator that binds more tightly than lets. Semantically the cell-separator operator behaves the exact same as tuple commas; the only difference is precedence (I think they will need to be different given that https://github.com/hazelgrove/hazel/issues/757 suggests tuple commas should be lowest). In school mode, the cells get spliced together and evaluated; then, if you want to show individual results for each cell, you can extract the evaluated tuple components from the ModelResult (are we going to show results for anything other than the student impl?). 

We also talked about not internalizing cell separators and threading evaluator environments through cells, but this would require additional plumbing that we shouldn't try to bite off right now. We can revisit this decision later. For now, the only debt we take on right now is a second internal tuple operator.

**Comment by cyrus-** [comment]
School mode actually needs to make multiple calls to the evaluator (running tests with student solution, then separately with instructor solution, etc.), so exposing a simple way to make multiple calls to the worker with a term is necessary.

**Comment by cyrus-** [comment]
Showing the result of student cell would then also be straightforward, just a separate run without anything following it.

**Comment by dm0n3y** [comment]
I see. Ok then I propose we add a string key (eg `"student_impl"`, `"instructor_solution"`, etc) to the evaluator request datatype and make the `ModelResult` a map from keys to evaluator responses.

**Comment by cyrus-** [comment]
Sure, that works. The values in that map should tell you the state of the request, maybe like Pending/TimedOut/Finished, so that we can put in UI to indicate that for long-running requests / show timeout feedback.

**Comment by cyrus-** [comment]
Unless there is a trick I'm missing, you can't run this PR from a `file:///` URL due to browser security restrictions.

It does seem to work okay if you spawn up a server, e.g. using `python3 -m http.server 8000` in the `_build/default/src/haz3lweb/www/index.html` directory. I guess this is fine, but we should modify the Makefile and README.

**Comment by cyrus-** [comment]
Actually, getting really odd results when running it from localhost. Sometimes it works, sometimes it doesn't. Seems to be some sort of race condition. Works consistently when I add a print_endline and have the console open so I think it may have something to do with timeouts / fast path logic? I can show you on screen sharing (maybe, if that doesn't affect the race...) if you can't reproduce. I've been able to do it on both my Linux desktop and Mac, and in both Chrome and Firefox...

**Comment by cyrus-** [comment]
If this is going to take a long time to debug, can we get a PR that is just the new evaluator but without the web worker stuff? Current haz3l-tests evaluator doesn't work if you have tests in your code. Making it difficult to make progress on school mode stuff now.

**Comment by cyrus-** [comment]
Hm, problem also seems to go away if serving a `make release` version of the code. Not sure if that's just because it is faster. Very odd. But given that I'm blocked on this, I'm going to merge this into my branch for now.

**Comment by mirryi** [comment]
For me it seemed like one evaluation would succeed, and then the rest would just timeout. I was trying to figure out where in the worker pipeline it was failing but still haven't a good idea.

**Pull request merged**
