### PR TITLE
Junit test reporter

### PR DESCRIPTION
**Pull request by 7h3kk1d**

### CODE REVIEW

**Comment by cyrus-** [comment]
The current output on a failed test seems to show more information (the expected and actual value): 

https://github.com/hazelgrove/hazel/actions/runs/7981272446/job/21792731140

Not sure this is a net win despite the red/green coloring?

**Comment by 7h3kk1d** [comment]
> The current output on a failed test seems to show more information (the expected and actual value):
> 
> https://github.com/hazelgrove/hazel/actions/runs/7981272446/job/21792731140
> 
> Not sure this is a net win despite the red/green coloring?

The new one should show that below

[Screencast from 2024-02-27 15-25-39.webm](https://github.com/hazelgrove/hazel/assets/995429/874ef5ff-abe9-4f6b-a05f-05518580714d)

**Comment by cyrus-** [comment]
Ah I see -- you have to click Raw Output.

**Review by cyrus- — APPROVED** [review]
Looks good to me -- you can merge into `junit-tests` after removing the failing test and we can then merge into `dev` from there?

**Pull request merged**
