### PR TITLE
Make scroll to caret more selective

### LINKED ISSUE #1085: be more selective about scroll-to-caret
Select-all doesn't scroll to caret in vscode and probably shouldn't here. Especially true if quadruple-click selects all, as there is a significant possibility of accidental quadclick and incumbent context loss

### PR DESCRIPTION
**Pull request by Negabinary**
This fixes #1085. It was getting too annoying on the stepper.

### CODE REVIEW

**Comment by Negabinary** [comment]
@disconcision do you understand what happened with the checks here?

**Comment by cyrus-** [comment]
Sometimes it is weird if two pushes come in too quickly in succession? I thought I had fixed that but seems not perfectly. You can just re-run the job if that happens (already did that in this case).

**Comment by disconcision** [comment]
is there a reason this couldn't be implemented as a State variable triggered via scheduled_action? as opposed to threading queue_scroll_to_caret through several things?

also i think the logic mapping actions to queue_scroll_to_caret() should probably be factored out ala reevaluate_post_update as opposed to called in in update on a per-case basis, better separation of concerns

**Comment by disconcision** [comment]
I'm a bit confused about what actions queue_scroll_to_caret is called in too... like why is it called in SetShowBackpackTargets?

**Comment by disconcision** [comment]
@Negabinary could you take a look at this diff? https://github.com/hazelgrove/hazel/pull/1024/commits/07aeb0b833cd432d14c276634f7f5b5e74d133ab
i removed the threading and just wrote a single predicate (Update.should_scroll_to_caret) which is called in Main. does this approach miss anything?

**Comment by cyrus-** [comment]
@disconcision can you make a separate PR for that to keep track better?

**Comment by disconcision** [comment]
@cyrus- there's a substantial intersection between this and TyDi, so that would require mostly redoing the change from scratch. this was an attempt to do it quickly and avoid blocking a TyDi merge. i can separate it out, but I might not get to it for a bit.

**Comment by disconcision** [comment]
@cyrus- unless you mean just separate that last commit as a post-tydi PR, in which case i can do that rn

**Comment by disconcision** [comment]
@cyrus- created new PR on top of TyDi #1149

**Pull request merged**
