### PR TITLE
Menhir parser

### PR DESCRIPTION
**Pull request by green726**

### CODE REVIEW

**Comment by cyrus-** [comment]
@green726 I'm looking at upping our testing game and would like to be able to write tests in concrete syntax. We can run strings through tylr to get a UExp, but there is no equivalent for internal expressions. How do you feel about finishing up this PR to provide a parser for DHExp terms?

**Comment by green726** [comment]
> @green726 I'm looking at upping our testing game and would like to be able to write tests in concrete syntax. We can run strings through tylr to get a UExp, but there is no equivalent for internal expressions. How do you feel about finishing up this PR to provide a parser for DHExp terms?

@cyrus- Sure! IIRC, the menhir parser was pretty much fully written and I just needed to translate the AST output by Menhir into the DHExp/DHPat terms. However, I may not be able to get much work done on this in the next few weeks; I have a paper due back with revisions to a journal in <2 weeks (solo project I submitted to Journal of Computer Languages), and I still have a lot of writing left to do. Once I get that paper in though, I should hopefully be able to finish this pretty quickly. Maybe we could do a zoom or I could hop on to office hours at some point to discuss this more?

**Comment by cyrus-** [comment]
@green726 okay sounds good. (let me know if you want any feedback on your paper!)

**Comment by green726** [comment]
> @green726 okay sounds good. (let me know if you want any feedback on your paper!)

Thank you! I appreciate the offer and will let you know when it's almost done.

**Comment by cyrus-** [comment]
Closing in favor of #1220 since the merge was already done there.

**Pull request closed without merging**
