### PR TITLE
use Fira Code SemiBold for bold, fixing cursor placement issue on FF

### LINKED ISSUE #379: cursor positioning bugs
still seeing cursor positioning bugs on Firefox, but not Chrome -- 
Screenshot from 2020-06-29 14-52-08

### PR DESCRIPTION
**Pull request by cyrus-**
Fixes #379

### CODE REVIEW

**Comment by dm0n3y** [comment]
Intense bold. Is this what it looks like on Linux?
image

**Comment by cyrus-** [comment]
yeah -- what did it look like before on Mac?

**Comment by dmoon1221** [comment]
image

**Review by dm0n3y — APPROVED** [review]

**Comment by cyrus-** [comment]
those look identical to me

**Comment by dm0n3y** [comment]
image

**Comment by dm0n3y** [comment]
My bad, pasted the same screenshot

**Comment by cyrus-** [comment]
ah okay. yeah that's definitely different -- the old version doesn't really distinguish the keywords much at all. we could try Fira Code Medium, that might be a little less bold if you like that better

**Comment by cyrus-** [comment]
Screenshot from 2020-07-02 11-43-16

this is Fira Code Medium

**Comment by dm0n3y** [comment]
I'm fine with semi bold for now, might be better to have the distinction clearer.

**Review by hannahpotter — APPROVED** [review]

**Pull request merged**
