### PR TITLE
Slides

### PR DESCRIPTION
**Pull request by Negabinary**
This (hastily) adds the ability to put images on scratch slides, or examples slides.

image

Images are specified using hard-coded urls in init.ml

### CODE REVIEW

**Comment by disconcision** [comment]
vibe

**Comment by cyrus-** [comment]
Is it significantly harder to have it be an arbitrary vdom node rather than just an image?

**Comment by Negabinary** [comment]
> Is it significantly harder to have it be an arbitrary vdom node rather than just an image?

oh I see, probably not much harder, no; I'll take a look shortly

**Comment by Negabinary** [comment]
so it's harder to save the arbitrary node because there's no sexp for Node.t; but I might be able to make it just hard-coded today, never going through the save file if that works?

**Comment by cyrus-** [comment]
Yeah that should be fine. I'll spend time tomorrow getting everything
prepped.

**Comment by cyrus-** [comment]
Merged as part of #1164

**Pull request closed without merging**
