### PR TITLE
Shmyth interactive

### PR DESCRIPTION
**Pull request by dm0n3y**

### CODE REVIEW

**Comment by cyrus-** [comment]
@disconcision we should chat about the dev process here -- do you want to merge shmtyh into dev soon? (I'd argue we should, but we need to be aware of the dev burden that might create)

**Comment by disconcision** [comment]
@cyrus soon ish?

1. the assert branch bugs should be fixed first. i've probably found one or two other assert bugs which are only on the shmyth kanban and and not on the asserts PR... I'll collate those.

2. the hacky stuff on the smyth side and the glue code isn't a huge deal to merge in, in that it won't pollute anything else; but i'll do some quick cleanup here this week.

3. I've only looked at part of the interface stuff that @dmoon1221 did; we'll coordinate on getting that in shape

**Comment by cyrus-** [comment]
@disconcision is this PR still relevant given newer work on Assistant, or should we close it?

**Comment by disconcision** [comment]
@cyrus I guess it's a matter of perspective.... what do you mean by relevant exactly? everything here is fully orthogonal to existent assistant work, and i still pull up this branch to show people.

**Comment by cyrus-** [comment]
Yeah the branch can stick around, was just asking about the PR into `dev` -- are we planning to get this merged into `dev` in some capacity or leave it as a branch?

**Comment by cyrus-** [comment]
Closing this PR since it isn't on track for integration with dev/haz3l directly, can always pull it back up as needed.

**Pull request closed without merging**
