### PR TITLE
Haz3l tests new evaluator

### PR DESCRIPTION
**Pull request by dedbox**
Copies in files for the new evaluator.

Everything is nearly ready to go, but I'm totally burnt and can't quite figure out how to deal with some of the older files that are no longer relevant but prevent compilation, like `Program.re`. If anyone can figure out that part quickly, it's done.

### CODE REVIEW

**Comment by mirryi** [comment]
Can we just remove both hazelcore and hazelweb after/in this?

**Comment by mirryi** [comment]
@dedbox Can you also make the PR to be into `haz3l-tests`, not `dev`?

**Comment by dm0n3y** [comment]
taking a look at resolving merge conflicts

**Comment by dm0n3y** [comment]
I'll take over merging

**Pull request merged**
