### PR TITLE
Rename MetaVarGen to IDGen

### PR DESCRIPTION
**Pull request by mirryi**

### CODE REVIEW

**Comment by mirryi** [comment]
@disconcision Is this ready to merge?

**Comment by disconcision** [comment]
@cyrus @mirryi I think this is good to go. At least, modulo the last build failing, not sure what's going on there.

Here are some instructions we can post to slack regarding other people merging it:

To simplify merging in these changes, you can perform the following actions before merging:
1. rename the file MetaVarGen.re to IDGen.re
2. rename the file MetaVarGen.rei to IDGen.rei
3. find/replace "MetaVarGen" to "IDGen" across the whole codebase
4. find/replace "u_gen" to "id_gen" across the whole codebase

(@mirryi can you think of anything I missed here?)

I think if these are done the merge should probably go through without conflicts in approximately all cases.

**Comment by mirryi** [comment]
Yeah, not sure why the build is failing, seems to be some odd git issue. Just to confirm, the PR adds KeywordID, but we're not doing anything with it quite yet, right? Just making sure I didn't miss anything in my brief skim over. Otherwise I think that's it.

**Comment by disconcision** [comment]
@mirryi yes, it's just to isolate the big renaming to lessen the confusion for people working on other branches. i'm taking a look at the build failure now, it is slightly weird

**Review by cyrus- — APPROVED** [review]

**Pull request merged**
