### PR TITLE
Clipboard (Copy, Paste, Cut)

### PR DESCRIPTION
**Pull request by disconcision**
d give this a quick try before I merge pls

### CODE REVIEW

**Comment by disconcision** [comment]
@dmoon1221 okay there's actually still a consistency issue with this; you can still end up with non-shards in the backpack if you backspace on a selection containing an incomplete tile which has a bidelimited tile say "let x =". how straightforward would it be to change destruct to take these apart? probably want to do it via a flag as I can see going back and forth on this

**Comment by dm0n3y** [comment]
should be straightforward. add another step that breaks apart the `to_pick_up` incomplete tiles produced in https://github.com/hazelgrove/hazel/blob/haz3l-tests/src/core/zipper/Zipper.re#L182

**Comment by disconcision** [comment]
@dmoon1221 can you sanity check that change?

**Comment by dm0n3y** [comment]
looks good

**Comment by disconcision** [comment]
Merging this. Destruct now removes all children. Pick-up is bound to Ctrl-P.

**Pull request merged**
