### PR TITLE
update ocaml to 4.12.1

### PR DESCRIPTION
**Pull request by coned**

### CODE REVIEW

**Comment by cyrus-** [comment]
@coned There are instructions for when we update to a new version of OCaml here: https://github.com/hazelgrove/hazel/blob/dev/UPDATING.md. Can you go through those and make sure we are doing that / update the instructions if anything is out of date (as part of this PR)? I think at least the instructions about travis need to be updated to talk about github actions.

**Review by cyrus- — CHANGES_REQUESTED** [review]
see comment

**Comment by coned** [comment]
I decided to update ocaml to 4.12.1 because we have a dependency rtop which only supports up to 4.12.1. I try to make least changes. So, only necessary packages are updated. The only big change is merlin (3.6.1 -> 4.4-412).

**Review by cyrus- — CHANGES_REQUESTED** [review]
Can you also update the UPDATING.md file with up-to-date instructions for future upgrades? Some things there are no longer relevant, e.g. the vscode extension stuff.

**Pull request merged**
