### PR TITLE
Exercise Mode Editing Capabilities

### LINKED ISSUE #813: Add ability to edit exercise title

### PR DESCRIPTION
**Pull request by russell-rozenbaum**
**Added Features**

Adds ability to edit several exercise mode features:
- Title
- Module name
- Prompt
- Number of Mutation Tests
- Required Tests
- Point Distributions

Also implements the following:
1. Exercise's storage keying system now uses UUIDs rather than (string, int) pairs. *Note: this change removes the previous version field, represented by the int in the pair of the old keying system 
3. persistent_state type in exercise mode has been made into a record. Along with the zipper position and editors it stores the title and list of mutants. This allows for mutants to be persisted and unpersisted upon saving and loading to and from local storage.

**Caveats**
- Exercise modules must have a hardcoded UUID in their spec file to save and load properly. A potential solution can be to initialize a UUID and update the spec when first loading. This would require mutating the spec file however. This shouldn't prove to be much of an issue when creating new exercises.
- Future implementations requiring saving and loading mutable features to and from storage will need to be added in the record and persisted/unpersisted properly in their respective functions. This isn't as much of a pitfall, as it is a note to help future implementations.

### CODE REVIEW

**Comment by cyrus-** [comment]
@russell-rozenbaum did you intend to close this issue?

**Comment by russell-rozenbaum** [comment]
I've added more changes beyond just the title editor to this branch, to be exact I added some implementations to adding and deleting buggy implementations, so I wasn't sure whether to move those commits to a different branch or finish them out fully before opening this pull request

**Comment by russell-rozenbaum** [comment]
Commit [968fe1c] is the one I'd like to merge. The last 2 commits add the ability to add/delete buggy implementations, which I'll start on another branch. The problem with the current version is a bug that occurs when adding a wrong implementation (which is itself an editor) and then I believe the program does not know where to put the cursor on page reload since the editors are reset (the one previously added, now deleted on page reload), and results in an infinite loading screen. Besides this, I still want to add the ability to edit the hints associated with buggy implementations, which right now defaults to "no hint available".

**Comment by cyrus-** [comment]
@russell-rozenbaum there are some merge conflicts and a build failure here

**Comment by cyrus-** [comment]
@facundoy The markdown editor isn't inserting line breaks correctly (ignores them).

**Comment by cyrus-** [comment]
@facundoy looks like the big task remaining here is to fix the merge conflicts. should mostly be moved files and basic re-org but feel free to reach out to @Negabinary if you have any questions.

**Comment by russell-rozenbaum** [comment]
Closing this PR in favor of #1444 (resolved merge conflicts and other bug fixes)

**Pull request closed without merging**
