### PR TITLE
Replace InvalidInput codes with proper EvaluatorError type

### LINKED ISSUE #549: Replace InvalidInput codes with proper EvalError type
The evaluator currently uses an `InvalidInput(int)` variant of `Evaluator.result` for returning from evaluation branches that shouldn't ever execute. We should replace those codes with a more informative `EvalError` type.

### PR DESCRIPTION
**Pull request by mirryi**
Resolves #549.

### CODE REVIEW

**Comment by disconcision** [comment]
definitely a positive change, but i do wonder why we don't just throw exceptions here, given that all these conditions are non-recoverable and indicate an error in either the typechecker, elaborator, or evaluator.

(signed T. looking to reduce the height of the evaluator monad transformer stack)

**Comment by mirryi** [comment]
Perhaps it was initially the idea that the core stuff (typechecking, elaboration, evaluation) should be purely functional, and to move all the user-facing stuff out (in this case, notifying the user/developer of the bug). Just a guess though.

**Comment by cyrus-** [comment]
Yeah that decision was a remnant of doing everything in Coq at one point -- let's refactor it to use an exception instead.

**Comment by mirryi** [comment]
Then I should just move `Program.InvalidInput` exception directly into `Evaluator` and raise immediately?

**Comment by cyrus-** [comment]
Yep that makes sense. You should be able to reuse the error code datatype you defined here.

**Review by cyrus- — APPROVED** [review]

**Comment by cyrus-** [comment]
Thanks, Eric!

**Pull request merged**
